#!/usr/bin/env bash

target="$1"
cmp_branch="$2"
if [ -z "$cmp_branch" ]; then
        cmp_branch="-"
fi

bench_arg() {
        [ -n "$target" ] && echo "--bench $target"
}

git checkout $cmp_branch
cargo bench $(bench_arg)

git checkout -
cargo bench $(bench_arg)
