#!/bin/bash

target="$1"
if [ -z "$target" ]; then
        echo "Target is empty. Exiting."
        exit 1
fi
cmp_branch="$2"
if [ -z "$cmp_branch" ]; then
        cmp_branch="-"
fi

git checkout $cmp_branch
cargo bench --bench $target -- --save-baseline $target
CARGO_PROFILE_RELEASE_DEBUG=true cargo flamegraph \
        --features smol_bench -o "flamegraph-$target-before.svg" \
        --bench $target \
        -- --bench

git checkout -
cargo bench --bench $target -- --save-baseline $target
CARGO_PROFILE_RELEASE_DEBUG=true cargo flamegraph \
        --features smol_bench -o "flamegraph-$target-after.svg" \
        --bench $target \
        -- --bench
